SELECT * FROM dane

SELECT 'Total', COUNT(*) AS Counter FROM dane
UNION
SELECT 'FirstName1', COUNT(DISTINCT FirstName1) AS Counter FROM DANE
UNION
SELECT 'FistName2', COUNT(DISTINCT FirstName2) AS Counter FROM DANE
UNION
SELECT 'Country', COUNT(DISTINCT Country) AS Counter FROM DANE
UNION
SELECT 'Region', COUNT(DISTINCT Region) AS Counter FROM DANE
UNION
SELECT 'Pet', COUNT(DISTINCT Pet) AS Counter FROM DANE
UNION
SELECT 'Profession', COUNT(DISTINCT Profession) AS Counter FROM DANE