CREATE TABLE IF NOT EXISTS MenNames (Id INTEGER PRIMARY KEY AUTOINCREMENT, Name TEXT);
CREATE TABLE IF NOT EXISTS WomenNames (Id INTEGER PRIMARY KEY AUTOINCREMENT, Name TEXT);
CREATE TABLE IF NOT EXISTS Countries (Id INTEGER PRIMARY KEY AUTOINCREMENT, Name TEXT);
CREATE TABLE IF NOT EXISTS Regions (Id INTEGER PRIMARY KEY AUTOINCREMENT, Name TEXT);
CREATE TABLE IF NOT EXISTS Pets (Id INTEGER PRIMARY KEY AUTOINCREMENT, Name TEXT);
CREATE TABLE IF NOT EXISTS Professions (Id INTEGER PRIMARY KEY AUTOINCREMENT, Name TEXT);

DELETE FROM WomenNames; INSERT INTO WomenNames (Name) SELECT DISTINCT FirstName1 FROM dane;
DELETE FROM MenNames; INSERT INTO MenNames (Name) SELECT DISTINCT FirstName2 FROM dane;
DELETE FROM Countries; INSERT INTO Countries (Name) SELECT DISTINCT Country FROM dane;
DELETE FROM Regions; INSERT INTO Regions (Name) SELECT DISTINCT Region FROM dane;
DELETE FROM Pets; INSERT INTO Pets (Name) SELECT DISTINCT Pet FROM dane;
DELETE FROM Professions; INSERT INTO Professions (Name) SELECT DISTINCT Profession FROM dane;

DROP TABLE Peoples;
CREATE TABLE IF NOT EXISTS Peoples AS 
SELECT D.email, D.Phone, D. BirthDate, D.PAN, D.Company, D.PostalZip, D.GUID, D.Colour, D.Credit, D.RUT, D."Group",
	   W.Id AS WomenNameId, M.Id AS MenNameId, C.Id AS CountryId, R.Id AS RegionId, P.Id AS PetId, S.Id AS ProfessionId
FROM dane AS D
   LEFT JOIN WomenNames AS W ON D.FirstName1 = W.Name
   LEFT JOIN MenNames AS M ON D.FirstName2 = M.Name  
   LEFT JOIN Countries AS C ON D.Country = C.Name
   LEFT JOIN Regions AS R ON D.Region = R.Name
   LEFT JOIN Pets AS P ON D.Pet = P.Name
   LEFT JOIN Professions AS S ON D.Profession = S.Name;
   
SELECT * FROM Peoples;